Category 3: String Containment Predicates (contains, starts with, ends with)
LLNL/hatchet-tutorial pull request #8
Opened 2022-06-23 02:14 UTC by vanessalama09

This PR is created to add Jupyter Notebooks for Category 3 (string containment predicates) of the Hatchet Query Language. Two notebooks and their corresponding markdown files with documentation for the String-based Dialect and the base Hatchet Query are included.

2022-06-23 23:25 UTC, MichaelMcKinsey1 approved these changes

2022-06-30 20:06 UTC, Treece-Burgess commented on notebooks/common/documentation/base-query-language-03.md
> +The **Query Language** finds all paths in a call graph that match properties described by the query applied to profiling data. It enables Hatchet’s Jupyter notebook-based interactive visualization to
Simplify should be simplifies I believe.

2022-06-30 20:06 UTC, Treece-Burgess commented on notebooks/query-language-base/07.03.predicate_combination_disjunction_complement.ipynb
> +       "This query type allows a user to search for nodes that match the complement of a query node predicates using the NOT logical operator.\n",
Should predicates be predicate?

2022-07-06 05:00 UTC, slabasan approved these changes

2022-07-06 05:02 UTC, slabasan requested changes
Can you provide a more descriptive commit message? I think it might have been affected with trying to resolve the merge commits.

2022-07-06 15:56 UTC, slabasan approved these changes

2022-07-06 15:57 UTC, merged